// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// initialChecks
Rcpp::List initialChecks(const Rcpp::List& Y0, const Rcpp::List& Y1, const Rcpp::NumericMatrix& P0, const Rcpp::NumericMatrix& S0, const Rcpp::List& params, const Rcpp::String& diss, long long seed);
RcppExport SEXP _ProbKMAcpp_initialChecks(SEXP Y0SEXP, SEXP Y1SEXP, SEXP P0SEXP, SEXP S0SEXP, SEXP paramsSEXP, SEXP dissSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String& >::type diss(dissSEXP);
    Rcpp::traits::input_parameter< long long >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(initialChecks(Y0, Y1, P0, S0, params, diss, seed));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_ProbKMAModule();

static const R_CallMethodDef CallEntries[] = {
    {"_ProbKMAcpp_initialChecks", (DL_FUNC) &_ProbKMAcpp_initialChecks, 7},
    {"_rcpp_module_boot_ProbKMAModule", (DL_FUNC) &_rcpp_module_boot_ProbKMAModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProbKMAcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
