# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialChecks <- function(Y0, Y1, P0, S0, params, diss, seed) {
    .Call(`_ProbKMAcpp_initialChecks`, Y0, Y1, P0, S0, params, diss, seed)
}

